---
- hosts: all

  environment:
    http_proxy: http://62.81.0.143:80
    https_proxy: http://62.81.0.143:80 
  
  tasks:

  - name: "Add entries to /etc/hosts"
    # become: true
    # become_method: su
    lineinfile: dest=/etc/hosts
                line='{{item}}'
    with_items:
      - ""
      - "### Backup"
      - "192.168.2.2 server01"
      - "192.168.2.3 server01-backup"

  - name: Configure proxy 
    command: subscription-manager config --server.proxy_hostname=62.81.0.143 --server.proxy_port=80

  - name: Subscribe 
    command: subscription-manager register --username {{ rhn_user }} --password {{ rhn_pass }} --force
    
  - name: Attach pool 
    #command: subscription-manager attach --pool=8a85f98144844aff014488d059f61625
    command: subscription-manager attach 
  
  - name: Disable repos 
    command: subscription-manager repos --disable=*

  - name: Enable repos 
    command: subscription-manager repos --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-7-server-rpms 
  
  - name: Copy required RPMs
    copy:
      src: rpms
      dest: /root/      

  # - name: install the EPEL repo
  #   yum:
  #     name: /root/rpms/epel-release-latest-7.noarch.rpm
  #     state: present

  - name: "Install Nagios NRPE"
    yum: state=present name={{ item }}
    with_items:
    - /root/rpms/nagios-common-4.2.4-2.el7.x86_64.rpm
    - /root/rpms/nrpe-2.15-7.el7.x86_64.rpm


  - name: Push NRPE configuration
    copy:
      src: config_files/nrpe.cfg
      dest: /etc/nagios/nrpe.cfg
      owner: root
      group: root
      mode: 0644

  - name: Create bin folder
    file:
      path: /opt/nagios/bin/
      state: directory
      mode: 0755

  - name: Push NRPE check scripts
    unarchive:
      src: bin/nagios_checks.tar
      dest: /opt/nagios/bin/

  - name: enable service NRPE
    systemd:
      name: nrpe
      state: started 
      enabled: yes

  - name: "Install NTP"
    yum: state=present name={{ item }}
    with_items:
    - /root/rpms/autogen-libopts-5.18-5.el7.x86_64.rpm
    - /root/rpms/ntpdate-4.2.6p5-25.el7_3.2.x86_64.rpm
    - /root/rpms/ntp-4.2.6p5-25.el7_3.2.x86_64.rpm

  # - name: Disable chronyd
  #   systemd:
  #     name: chronyd
  #     state: stopped 
  #     enabled: no

  - name: Push NTP configuration
    copy:
      src: config_files/ntp.conf
      dest: /etc/ntp.conf
        
  - name: enable service ntpd
    systemd:
      name: ntpd
      state: started 
      enabled: yes