---
- hosts: all

  environment:
    http_proxy: http://{{ proxy_user }}:{{ proxy_password }}@{{ http_proxy }}:80
  
  tasks:

  - name: Copy required RPM
    copy:
      src: rpms/httpd-2.2.15-59.el6.centos.x86_64.rpm
      dest: /root/

  # - name: Install httpd RPM
  #   yum: name=httpd

  - name: Install httpd RPM
    yum: state=present name={{ item }}
    with_items:
    - /root/rpms/httpd-2.2.15-53.el6.x86_64.rpm

  - name: start httpd service
    service: name=httpd state=started

  - name: Open Port 80
    firewalld: service=http permanent=true state=enabled

  - name: Start firewalld service
    service: name=firewalld state=restarted